# Generated by Django 4.1 on 2022-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=50)),
                ('image', models.CharField(default='No image', max_length=100)),
                ('price', models.CharField(default='-', max_length=10)),
                ('release_date', models.CharField(default='-', max_length=10)),
                ('lte_exists', models.CharField(default='-', max_length=10)),
                ('slug', models.SlugField(default='-', max_length=200)),
            ],
        ),
    ]
