name: Django testing and deploy


on:
  push:
    branches: [video]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check update
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install pip
        run: pip install -r requirements.txt

      - name: check code
        run: flake8 main

      - name: testing
        run: python manage.py test
